Fixed a bug, and added support for Accumulo Proxy.

diff --git a/acc_test_sw_install b/acc_test_sw_install
--- a/acc_test_sw_install
+++ b/acc_test_sw_install
@@ -1,19 +1,22 @@
 #!/bin/bash
 
-# March 2021 - Gene Weber
+# April 2021 - Gene Weber
 # This script installs all software necessary to run an Accumulo 2.0.1 baseline test.
 # This includes: Maven 3.6.3, Zookeeper 3.6.2, hadoop 3.1.2, accumulo 2.0.1, and accumulo-testing 2.0
+# It optionally installs Accumulo Proxy 2.0.0
 
 # These scripts should be relatively Linux hardware platform independent.
 # All configuration in done in the acc_test.conf file.
 
 # Assumptions/Requirements:
 # 1. These scripts were tested with openjdk 1.8.
-# 2. These scripts require gcc version 5.1 or greater for accumulo native library compile.
-# 3. These scripts require pdsh.
-# 4. These scripts require patch.
-# 5. These scripts require that the user have read, write, and execute permission on local NVMe drives.
-# 6. These scripts assume CentOS 7.
+# 2. These scripts were tested on AWS.
+# 3. These scripts require gcc version 5.1 or greater for accumulo native library compile.
+# 4. These scripts require pdsh.
+# 5. These scripts require patch.
+# 6. These scripts require that nodes have access to both a shared file system and at least one local drive.
+# 7. These scripts require that the user have read, write, and execute permission on local drives.
+# 8. These scripts assume CentOS 7.
 
 # vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
 # >>> Run some checks and tests before starting actual installation
@@ -66,40 +69,55 @@ fi
 
 # Verify that all needed tar and zip files exist.
 ALL_PRESENT=true
-if [ ! -f $HADOOP ]; then
+# Check if Hadoop is installed, or if the installation file is present.
+if [ ! -d $HADOOP_HOME ] && [ ! -f $HADOOP ]; then
   ALL_PRESENT=false
   echo ""
   echo "$HADOOP is not present. It can be downloaded here:"
   echo "https://archive.apache.org/dist/hadoop/common/"
   echo ""
 fi
-if [ ! -f $ZOOKEEPER ]; then
+# Check if Zookeeper is installed, or if the installation file is present.
+if [ ! -d $ZOO_HOME ] && [ ! -f $ZOOKEEPER ]; then
   ALL_PRESENT=false
   echo ""
   echo "$ZOOKEEPER is not present. It can be downloaded here:"
   echo "https://zookeeper.apache.org/releases.html"
   echo ""
 fi
-if [ ! -f $ACCUMULO ]; then
+# Check if Accumulo is installed, or if the installation file is present.
+if [ ! -d $ACCUMULO_HOME ] && [ ! -f $ACCUMULO ]; then
   ALL_PRESENT=false
   echo ""
   echo "$ACCUMULO is not present. It can be downloaded here:"
   echo "https://accumulo.apache.org/downloads/"
   echo ""
 fi
-if [ ! -f $ACCUMULO_TESTS ]; then
+# Check if Accumulo Tests is installed, or if the installation file is present.
+if [ ! -d $ACCUMULO_TESTS_HOME ] && [ ! -f $ACCUMULO_TESTS ]; then
   ALL_PRESENT=false
   echo ""
   echo "$ACCUMULO_TESTS is not present. It can be downloaded here:"
   echo "https://github.com/apache/accumulo-testing"
   echo ""
 fi
-if [ ! -f $MAVEN ]; then
+# Check if Maven is installed, or if the installation file is present.
+if [ ! -d $MAVEN_HOME ] && [ ! -f $MAVEN ]; then
   ALL_PRESENT=false
   echo ""
   echo "$MAVEN is not present. It can be downloaded here:"
   echo "https://maven.apache.org/download.cgi"
   echo ""
+fi
+# Check if Accumulo Proxy is installed, or if the installation file is present.
+if [ $INSTALL_PROXY = true ]; then
+  if [ ! -d $ACC_PROXY_HOME ] && [ ! -f $ACC_PROXY_ZIP ]; then
+    ALL_PRESENT=false
+    echo ""
+    echo "$ACC_PROXY_ZIP is not present. It can be downloaded here:"
+    echo "https://github.com/apache/accumulo-proxy"
+    echo ""
+  fi
 fi
 if [ $ALL_PRESENT = false ]; then
   echo " Please install the needed tar and/or zip files."
@@ -528,6 +546,66 @@ if [ $INSTALL_TESTS = true ]; then
   echo "Building Apache Accumulo Testing SNAPSHOTs"
   echo ""
  $ACCUMULO_TESTS_HOME/bin/build
+fi
+
+# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
+# >>> Start Accumulo Proxy Installation and Configuration
+# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
+
+# Optional installation
+if [ $INSTALL_PROXY = true ]; then
+
+  echo ""
+  echo "Installing Accumulo Proxy"
+  echo ""
+  
+  # Check if the Accumulo Proxy software directory exists. If not, install it.
+  if [ ! -d $ACC_PROXY_HOME ]; then
+    HERE=`pwd`
+    # Check if the proxy main.zip has already been unzipped into a directory. If not, do so.
+    if [ ! -d $ACC_PROXY_BUILD ]; then
+      cd $INSTALL_DIR
+      unzip $HERE/$ACC_PROXY_ZIP
+      cd $ACC_PROXY_BUILD
+      mv pom.xml orig_pom.xml
+      # pom file requires two edits for Maven to compile successfully
+      cat orig_pom.xml | sed 's|<maven.compiler.release>8<\/maven.compiler.release>|\
+      <!\-\- <maven.compiler.release>8<\/maven.compiler.release> \-\->|' |\
+      sed 's|<version>.11,.<\/version>|<version>[1.8.0,)<\/version>|' > pom.xml
+      # Compile the proxy software.
+      mvn -X -e clean package -Ptarball 2>&1 | tee $HERE/mvn.log
+    fi
+    # If the tarball doesn't exist, something went wrong.
+    if [ ! -f target/$ACC_PROXY ]; then
+      echo ""
+      echo "Maven compile failed. Please review mvn.log"
+      echo ""
+      exit 1
+    else
+      rm $HERE/mvn.log
+      cd $INSTALL_DIR
+      # Untar the compiled proxy software.
+      tar -xvf accumulo-proxy-main/target/$ACC_PROXY
+      # Shorten the directory name.
+      mv `find $INSTALL_DIR/* -maxdepth 0 -type d  | grep "proxy-2"` $ACC_PROXY_HOME
+    fi
+    cd $HERE
+  fi
+  cp -n $ACC_PROXY_HOME/conf/proxy.properties $ACC_PROXY_HOME/conf/orig_proxy.properties
+  
+  # Create Accumulo Proxy Server node file
+  echo $ACC_PROXY_NODE > $INSTALL_DIR/acc_proxy_node
+  
+  # Create Accumulo Proxy properties patch files.
+  cat patch/proxy.properties.base |\
+   sed "s/ACC_DBASE_NAME/$ACC_DBASE_NAME/" |\
+   sed "s/ZOO_INSTANCES/$ZOO_INSTANCES/" |\
+   sed "s/ACC_USERNAME/$ACC_USERNAME/" |\
+   sed "s/ACC_PASSWD/$ACC_PASSWD/" \
+   > patch/proxy.properties.patch
+  
+  # Patch Accumulo proxy property file.
+  patch $ACC_PROXY_HOME/conf/proxy.properties patch/proxy.properties.patch
 fi
 
 #vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
